### ISSUE TITLE
RESETTING HQM PROGRESS

### ISSUE THREAD

**Issue by CaiganMythFang** [CaiganMythFang/TheFerretBusinessIssues#2]
Sometimes, something will cause HQM progress to corrupt, and your game will crash when loading that world. The following crash log is usually what will be seen : 

> java.lang.ArrayIndexOutOfBoundsException: -1
> hardcorequesting.network.DataReader.readData(DataReader.java:55)

or

> java.lang.NullPointerException: Exception in server tick loop
>   at hardcorequesting.QuestingData.<init>(QuestingData.java:524)
>   at hardcorequesting.QuestingData.readAllData(QuestingData.java:483)
>   at hardcorequesting.QuestingData$1.read(QuestingData.java:409)
>   at hardcorequesting.network.FileHelper.loadData(FileHelper.java:107)
>   at hardcorequesting.QuestingData.load(QuestingData.java:438)
>   at hardcorequesting.WorldEventListener.onLoad(WorldEventListener.java:23)
# **TO RESET YOUR HQM PROGRESS AND FIX THIS ISSUE** :

Make sure your Minecraft or server are both closed before doing this.
- **SINGLE PLAYER**
  - **FOR FTB LAUNCHER USERS**
    1. Open the FTB Launcher.
    2. Select The Ferret Business under Third Party Modpacks
    3. Above the list of modpacks, click Edit Mod Pack.
    4. In the new window, hit Open Folder
    5. This will open a file explorer window to the /mods/ directory for the modpack.
    6. Go up one directory, so you are in /minecraft/
    7. Open /saves/ and then the folder for your world. What you named the world at world creation is the name of the folder.
    8. Delete the /HardcoreQuesting/ folder.
  - **FOR CURSE VOICE USERS**
    1. Open the Curse Launcher
    2. Select the copy of The Ferret Business you had the crash
    3. Above the information for the modpack, to the right, should be a button marked [. . .], click it.
    4. In the dropdown, select Open Folder. This will put you in /minecraft/
    5. Open /saves/ and then the folder for your world. What you named the world at world creation is the name of the folder.
    6. Delete the /HardcoreQuesting/ folder
- **MULTIPLAYER**
  1. Open the world folder in the server directory.
  2. Delete /HardcoreQuesting/ folder.

Either way, you may need to re-enable questing by typing /hqm quest in game.

**Comment by Llorx** [comment]
Resetting the progress is not a fix, but a workaround. A dirty workaround... and worse when you have lost 2 times your progress already.

**Comment by CaiganMythFang** [comment]
I know what causes the progress database corruption sometimes, but not all the time. And the ONLY way to prevent that ONE type of corruption is by never updating, moving, or deleting quests around in HQM. This is due to how the HQM database is in 1.7. 

Thankfully, all the actual questing in TFB is done through Better Questing, whose quest progress database is a bit more robust in 1.7. Nothing else is really tracked via HQM anymore.

So technically, yes, it is a workaround. But there is not going to be any fix, because HQM development on 1.7 stopped years ago.

You can also very easily regain your lost progress in both HQM and BQ2 with the built in edit commands.
